name: TinyContext
channels:
  - defaults
dependencies:
  - python=3.9
  - chardet=5.2.0
  - cchardet=2.1.7
  - h5py=3.7.0
  - pandas=1.5.3
  - scipy=1.10.1
  - scikit-learn=1.2.2
  - matplotlib=3.7.1
  - pip=23.1.2
  - pip:
    - timeout_decorator
    - "--find-links https://download.pytorch.org/whl/torch_stable.html"
    - torch==2.0.1; sys_platform != "linux" and sys_platform != "win32"
    - torch==2.0.1+cpu; sys_platform == "linux" or sys_platform == "win32"
    - rouge-score==0.1.2
    # Manage the below packages over pip to avoid segmentation fault in transformers on Mac
    - jq==1.6.0
    - langchain==0.0.325
    - huggingface-hub==0.16.4
    - transformers==4.31.0
    - datasets==2.13.1
    - numpy==1.25.1
    - accelerate==0.24.0
    - peft==0.5.0
    #- bitsandbytes==0.41.1
    - trl==0.7.2